CC = gcc
CFLAGS = -std=c11 -O2 -Wall -Wextra

TARGET = main
OBJS = main.o coo.o solvers.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $<

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f *.o $(TARGET)
